t=(65,12,78,12,23,7)
print(t)
print("the 4th element in tuple is ",t[3], "and last 2nd element in tuple is ",t[-2])
print("count of 12 in tuple is ",t.count(12))
t1=("CCV","OOAD","DAA","PYTHON","NOSQL")
print(t1)
print("the max in tuple 1 is ",max(t)," also the max in tuple 2 is ",max(t1))
print("the min in tuple 1 is ",min(t)," also the min in tuple 2 is ",min(t1))